#!/usr/bin/env zsh
set -e

DATA_DIR="$HOME/.local/share/hashcheck"
DB="$DATA_DIR/hashes.db"

mkdir -p "$DATA_DIR"

chmod 700 "$DATA_DIR"

sqlite3 "$DB" <<EOF
CREATE TABLE IF NOT EXISTS files (
    path TEXT PRIMARY KEY,
    hash BLOB NOT NULL
);
EOF

chmod 600 "$DB"

SOURCE="${(%):-%x}"
while [ -L "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

LOG_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"

mkdir -p "$LOG_DIR/log"
chmod 2750 "$LOG_DIR/log"